<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    // define const
    const STATUS_SPECIAL = 2;
    const STATUS_ACTIVE = 1;
    const STATUS_DEACTIVE = 0;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    /**
     * The attributes that are mass assignable
     * @var array
     */

    protected $fillable = [
        'title', 'slug', 'image', 'summary', 'status', 'content','count_views', 'tags'
    ];

    /**
     * Define relationship between Category and article
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }

    public function comment()
    {
        return $this->hasMany('App\Models\Comment');
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function tag()
    {
        return $this->belongsToMany('App\Models\Tag');
    }



}
