<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    // define const
    const STATUS_ACTIVE = 1;
    const STATUS_DEACTIVE = 0;

    /**
     * Set default attributes
     * @var array
     */
    protected $attributes =  [
        'parent_id' => 0,
        'show_on_top' => 0
    ];

    protected $fillable = [
        'name', 'parent_id', 'status', 'to_top', 'slug'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        // before create
        static::creating(function ($category) {
            $category->updateSlug();
        });

        // before update
        static::updating(function ($category) {
            $category->updateSlug();
        });
    }

    public function updateSlug()
    {
        $this->slug = str_slug($this->name,"-");
    }

    /**
     * Define Relationship one-to-many
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function article()
    {
        return $this->hasMany('App\Models\Article');
    }

    public function children()
    {
        return $this->hasMany("App\Models\Category","parent_id","id");
    }

    public function parent()
    {
        return $this->belongsTo("App\Models\Category","parent_id","id");
    }

}
